"""
A script to store the constant variables used in the project.

List of constants:
1. MAX_LENGTH: The maximum sequence legnth of tokens generated by the decoder
2. IMAGE_SIZE: The size of the image fed into the CNN
3. START_TOKEN = The token that indicates the start of the sequence
4. END_TOKEN = The token that indicates the end of the sequence
"""
MAX_LENGTH = 26

IMAGE_SIZE = (299,299)

START_TOKEN = 'بب'

END_TOKEN = "نه"